sylius_resource:
    resources:
        synolia.command:
            driver: doctrine/orm
            classes:
                model: Synolia\SyliusSchedulerCommandPlugin\Entity\Command
                form: Synolia\SyliusSchedulerCommandPlugin\Form\CommandType
                repository: Synolia\SyliusSchedulerCommandPlugin\Repository\CommandRepository
        synolia.scheduled_command:
            driver: doctrine/orm
            classes:
                model: Synolia\SyliusSchedulerCommandPlugin\Entity\ScheduledCommand
                form: Synolia\SyliusSchedulerCommandPlugin\Form\ScheduledCommandType
